name       : ruamel_yaml
version    : 0.11.11
release    : 1
source     :
    - https://pypi.python.org/packages/fc/f1/7530ac8594453fc850e53580256f3152a8d8f2bb351bc3d0df8d7b53dbde/ruamel.yaml-0.11.11.tar.gz : ceb179bacbf32cd42449b102f962939ebae303f0418d4588368d0c0b374ff3a3
license    : MIT
summary    : ruamel.yaml is a YAML 1.2 loader/dumper package for Python.
component  : programming.python
description: |
    ruamel.yaml is a YAML parser/emitter that supports roundtrip preservation of comments, seq/map flow style, and map key order
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
    - pip
build      : |
    python setup.py build
install    : |
    pip install . --root=%installroot%
