name       : ruamel_yaml
version    : 0.16.13
release    : 3
source     :
    - https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-0.16.13.tar.gz : bb48c514222702878759a05af96f4b7ecdba9b33cd4efcf25c86b882cef3a942
license    : MIT
summary    : ruamel.yaml is a YAML 1.2 loader/dumper package for Python.
component  : programming.python
description: |
    ruamel.yaml is a YAML parser/emitter that supports roundtrip preservation of comments, seq/map flow style, and map key order
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
    - python-wheel
    - pip
build      : |
    python -m pip wheel --no-deps .
install    : |
    python -m pip install --root=%installroot% --no-deps --ignore-installed .
